name: Changelog

on: [pull_request]

jobs:
  add-changelog:
    name: Add to Changelog
    runs-on: ubuntu-latest
    steps:
    - uses: Sven65/Changelog-Actions@master
      if: github.event == 'closed' && github.event.pull_request.merged == true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
